---
- hosts: 192.168.77.101
  gather_facts: no
  become: yes
  roles: 
  - role: axonious
    vars:
      creds: NewCreds
  tasks:
  - debug: 
      msg: "This is nono task"
    tags: nono
  - shell: id
    register: out
  - debug: var=out